from __future__ import annotations

from dataclasses import dataclass
from typing import Dict
from typing import Tuple

import numpy as np


@dataclass
class MincoSample:
    z: np.ndarray
    z_dot: np.ndarray
    z_ddot: np.ndarray
    z_jerk: np.ndarray
    z_snap: np.ndarray
    z_crackle: np.ndarray
    piece_index: int
    local_time: float


class MINCO_S3NU:
    """
    Strict minimum-jerk MINCO-S3NU trajectory core.

    The sparse outer variables are intermediate points and segment times. This
    class never optimizes polynomial coefficients directly. For fixed
    conditions, intermediate points, and times, coefficients are generated by
    solving the MINCO linear system A(T)c = b(q,H,G).

    Each piece is a fifth-order polynomial for the flat output z=[x,y,psi]^T:

        z_i(s) = c0 + c1 s + c2 s^2 + c3 s^3 + c4 s^4 + c5 s^5

    Boundary conditions are PVA at head and tail. Interior constraints enforce
    position pass-through on both sides of every intermediate point and
    continuity of velocity, acceleration, jerk, and snap.
    """

    DERIVATIVE_COUNT = 6

    def __init__(self, dim: int = 3):
        self.dim = int(dim)
        if self.dim <= 0:
            raise ValueError("dim must be positive.")
        self.head_pva = None
        self.tail_pva = None
        self.inPs = None
        self.ts = None
        self.A = None
        self.b = None
        self._coeffs = None

    @staticmethod
    def _factorial_ratio(power: int, derivative: int) -> float:
        if power < derivative:
            return 0.0
        value = 1.0
        for item in range(power - derivative + 1, power + 1):
            value *= item
        return value

    @classmethod
    def basis(cls, t: float, derivative: int = 0) -> np.ndarray:
        if derivative < 0:
            raise ValueError("derivative must be nonnegative.")
        t = float(t)
        values = np.zeros(cls.DERIVATIVE_COUNT, dtype=float)
        for power in range(cls.DERIVATIVE_COUNT):
            if power < derivative:
                continue
            values[power] = (
                cls._factorial_ratio(power, derivative) *
                (t ** (power - derivative))
            )
        return values

    def set_conditions(self, head_pva, tail_pva):
        head_pva = np.asarray(head_pva, dtype=float)
        tail_pva = np.asarray(tail_pva, dtype=float)
        expected = (3, self.dim)
        if head_pva.shape != expected:
            raise ValueError(f"head_pva must have shape {expected}.")
        if tail_pva.shape != expected:
            raise ValueError(f"tail_pva must have shape {expected}.")
        self.head_pva = head_pva.copy()
        self.tail_pva = tail_pva.copy()
        self._invalidate_solution()

    def set_parameters(self, inPs, ts):
        if self.head_pva is None or self.tail_pva is None:
            raise RuntimeError("set_conditions must be called before set_parameters.")
        ts = np.asarray(ts, dtype=float).reshape(-1)
        if ts.size <= 0:
            raise ValueError("ts must contain at least one segment time.")
        if np.any(ts <= 0.0):
            raise ValueError("All segment times must be positive.")

        piece_count = int(ts.size)
        inPs = np.asarray(inPs, dtype=float)
        if piece_count == 1:
            inPs = np.empty((0, self.dim), dtype=float)
        else:
            expected = (piece_count - 1, self.dim)
            if inPs.shape != expected and inPs.shape == (self.dim, piece_count - 1):
                inPs = inPs.T
            if inPs.shape != expected:
                raise ValueError(f"inPs must have shape {expected}.")
            inPs = inPs.copy()

        self.ts = ts.copy()
        self.inPs = inPs
        self.A, self.b = self._build_linear_system(self.inPs, self.ts)
        solution = np.linalg.solve(self.A, self.b)
        self._coeffs = solution.reshape(piece_count, self.DERIVATIVE_COUNT, self.dim)

    def coefficients(self) -> np.ndarray:
        self._require_solution()
        return self._coeffs.copy()

    def coefficient_matrix(self) -> np.ndarray:
        self._require_solution()
        return self._coeffs.reshape(-1, self.dim).copy()

    def piece_count(self) -> int:
        self._require_solution()
        return int(self.ts.size)

    def duration(self) -> float:
        self._require_solution()
        return float(np.sum(self.ts))

    def sample(self, t: float) -> MincoSample:
        self._require_solution()
        piece_index, local_time = self._locate_piece(t)
        return self.sample_piece(piece_index, local_time)

    def sample_piece(self, piece_index: int, local_time: float) -> MincoSample:
        self._require_solution()
        piece_index = int(piece_index)
        if piece_index < 0 or piece_index >= self.piece_count():
            raise IndexError("piece_index out of range.")
        local_time = float(np.clip(local_time, 0.0, self.ts[piece_index]))
        coeff = self._coeffs[piece_index]
        values = [
            self.basis(local_time, derivative).reshape(1, -1) @ coeff
            for derivative in range(6)
        ]
        values = [value.reshape(self.dim) for value in values]
        return MincoSample(
            z=values[0],
            z_dot=values[1],
            z_ddot=values[2],
            z_jerk=values[3],
            z_snap=values[4],
            z_crackle=values[5],
            piece_index=piece_index,
            local_time=local_time,
        )

    def get_energy(self) -> float:
        self._require_solution()
        return self.energy_from_coefficients(self._coeffs, self.ts)

    def energy_gradients(self) -> Tuple[np.ndarray, np.ndarray]:
        self._require_solution()
        coeff_grad = np.zeros_like(self._coeffs)
        time_grad = np.zeros_like(self.ts)

        for piece_index, T in enumerate(self.ts):
            coeff = self._coeffs[piece_index]
            gram = self._jerk_gram(float(T))
            coeff_grad[piece_index] = 2.0 * gram @ coeff
            jerk_T = self.basis(float(T), 3).reshape(1, -1) @ coeff
            time_grad[piece_index] = float(jerk_T @ jerk_T.T)

        return coeff_grad, time_grad

    def propagate_gradients(self, coeff_grad, time_grad=None) -> Dict[str, np.ndarray]:
        """
        Propagate direct coefficient/time gradients to inPs and ts.

        Args:
            coeff_grad: direct dJ/dc with shape (M,6,dim), (6M,dim), or flat.
            time_grad: direct dJ/dT at fixed coefficients, shape (M,).

        Returns:
            dict containing gradients for `inPs`, `ts`, and the linear-system
            adjoint `lambda`.
        """
        self._require_solution()
        coeff_grad = np.asarray(coeff_grad, dtype=float)
        if coeff_grad.shape == self._coeffs.shape:
            coeff_grad_matrix = coeff_grad.reshape(-1, self.dim)
        elif coeff_grad.shape == (self.piece_count() * self.DERIVATIVE_COUNT, self.dim):
            coeff_grad_matrix = coeff_grad.copy()
        elif coeff_grad.size == self.piece_count() * self.DERIVATIVE_COUNT * self.dim:
            coeff_grad_matrix = coeff_grad.reshape(-1, self.dim)
        else:
            raise ValueError("coeff_grad has incompatible shape.")

        if time_grad is None:
            time_grad = np.zeros(self.piece_count(), dtype=float)
        else:
            time_grad = np.asarray(time_grad, dtype=float).reshape(-1)
            if time_grad.shape != self.ts.shape:
                raise ValueError("time_grad must have shape (M,).")

        adjoint = np.linalg.solve(self.A.T, coeff_grad_matrix)
        grad_inPs = self._propagate_to_inPs(adjoint)
        grad_ts = np.asarray(time_grad, dtype=float).copy()
        coeff_matrix = self._coeffs.reshape(-1, self.dim)
        for piece_index in range(self.piece_count()):
            dA_c = self._dA_dT_times_coefficients(piece_index, coeff_matrix)
            grad_ts[piece_index] -= float(np.sum(adjoint * dA_c))

        return {
            "inPs": grad_inPs,
            "ts": grad_ts,
            "lambda": adjoint.reshape(self.piece_count(), self.DERIVATIVE_COUNT, self.dim),
        }

    def get_energy_gradients_by_parameters(self) -> Dict[str, np.ndarray]:
        coeff_grad, time_grad = self.energy_gradients()
        result = self.propagate_gradients(coeff_grad, time_grad)
        result["coefficients"] = coeff_grad
        result["direct_ts"] = time_grad
        return result

    def _invalidate_solution(self):
        self.inPs = None
        self.ts = None
        self.A = None
        self.b = None
        self._coeffs = None

    def _require_solution(self):
        if self._coeffs is None or self.A is None or self.b is None:
            raise RuntimeError("MINCO parameters have not been set.")

    def _locate_piece(self, t: float) -> Tuple[int, float]:
        t = float(np.clip(t, 0.0, self.duration()))
        cumulative = np.cumsum(self.ts)
        piece_index = int(np.searchsorted(cumulative, t, side="right"))
        piece_index = min(piece_index, self.piece_count() - 1)
        start_time = 0.0 if piece_index == 0 else cumulative[piece_index - 1]
        return piece_index, t - start_time

    def _col_slice(self, piece_index: int) -> slice:
        start = piece_index * self.DERIVATIVE_COUNT
        return slice(start, start + self.DERIVATIVE_COUNT)

    def _add_basis_row(self, A, row: int, piece_index: int,
                       t: float, derivative: int, scale: float = 1.0):
        A[row, self._col_slice(piece_index)] += scale * self.basis(t, derivative)

    def _build_linear_system(self, inPs, ts):
        piece_count = int(ts.size)
        row_count = piece_count * self.DERIVATIVE_COUNT
        A = np.zeros((row_count, row_count), dtype=float)
        b = np.zeros((row_count, self.dim), dtype=float)

        row = 0
        for derivative in range(3):
            self._add_basis_row(A, row, 0, 0.0, derivative)
            b[row] = self.head_pva[derivative]
            row += 1

        for joint_index in range(piece_count - 1):
            T = float(ts[joint_index])
            next_piece = joint_index + 1
            q = inPs[joint_index]

            self._add_basis_row(A, row, joint_index, T, 0)
            b[row] = q
            row += 1

            self._add_basis_row(A, row, next_piece, 0.0, 0)
            b[row] = q
            row += 1

            for derivative in range(1, 5):
                self._add_basis_row(A, row, joint_index, T, derivative)
                self._add_basis_row(A, row, next_piece, 0.0, derivative, scale=-1.0)
                row += 1

        tail_piece = piece_count - 1
        tail_T = float(ts[tail_piece])
        for derivative in range(3):
            self._add_basis_row(A, row, tail_piece, tail_T, derivative)
            b[row] = self.tail_pva[derivative]
            row += 1

        if row != row_count:
            raise RuntimeError("Internal MINCO linear-system row count mismatch.")
        return A, b

    @classmethod
    def _jerk_gram(cls, T: float) -> np.ndarray:
        gram = np.zeros((cls.DERIVATIVE_COUNT, cls.DERIVATIVE_COUNT), dtype=float)
        for i in range(cls.DERIVATIVE_COUNT):
            ai = cls._factorial_ratio(i, 3)
            if ai == 0.0:
                continue
            for j in range(cls.DERIVATIVE_COUNT):
                aj = cls._factorial_ratio(j, 3)
                if aj == 0.0:
                    continue
                power = i + j - 5
                gram[i, j] = ai * aj * (T ** power) / power
        return gram

    @classmethod
    def energy_from_coefficients(cls, coeffs, ts) -> float:
        coeffs = np.asarray(coeffs, dtype=float)
        ts = np.asarray(ts, dtype=float).reshape(-1)
        if coeffs.shape[0] != ts.size or coeffs.shape[1] != cls.DERIVATIVE_COUNT:
            raise ValueError("coeffs must have shape (M,6,dim).")
        energy = 0.0
        for piece_index, T in enumerate(ts):
            gram = cls._jerk_gram(float(T))
            coeff = coeffs[piece_index]
            energy += float(np.trace(coeff.T @ gram @ coeff))
        return float(energy)

    def _propagate_to_inPs(self, adjoint: np.ndarray) -> np.ndarray:
        piece_count = self.piece_count()
        if piece_count == 1:
            return np.empty((0, self.dim), dtype=float)

        grad = np.zeros((piece_count - 1, self.dim), dtype=float)
        row = 3
        for joint_index in range(piece_count - 1):
            grad[joint_index] = adjoint[row] + adjoint[row + 1]
            row += 6
        return grad

    def _dA_dT_times_coefficients(self, piece_index: int,
                                  coeff_matrix: np.ndarray) -> np.ndarray:
        piece_count = self.piece_count()
        result = np.zeros_like(self.b)
        coeff = coeff_matrix[self._col_slice(piece_index)]

        if piece_index < piece_count - 1:
            row = 3 + 6 * piece_index
            T = float(self.ts[piece_index])
            for offset, derivative in zip([0, 2, 3, 4, 5], range(0, 5)):
                result[row + offset] += self.basis(T, derivative + 1) @ coeff

        if piece_index == piece_count - 1:
            row = 3 + 6 * (piece_count - 1)
            T = float(self.ts[piece_index])
            for derivative in range(3):
                result[row + derivative] += self.basis(T, derivative + 1) @ coeff

        return result
